// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: knowledge/knowledge.proto

/*
Package knowledge is a generated protocol buffer package.

It is generated from these files:
	knowledge/knowledge.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package knowledge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Knowledge service

type KnowledgeService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type knowledgeService struct {
	c    client.Client
	name string
}

func NewKnowledgeService(name string, c client.Client) KnowledgeService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "knowledge"
	}
	return &knowledgeService{
		c:    c,
		name: name,
	}
}

func (c *knowledgeService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "Knowledge.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Knowledge service

type KnowledgeHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterKnowledgeHandler(s server.Server, hdlr KnowledgeHandler, opts ...server.HandlerOption) error {
	type knowledge interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type Knowledge struct {
		knowledge
	}
	h := &knowledgeHandler{hdlr}
	return s.Handle(s.NewHandler(&Knowledge{h}, opts...))
}

type knowledgeHandler struct {
	KnowledgeHandler
}

func (h *knowledgeHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.KnowledgeHandler.Hello(ctx, in, out)
}
