// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: direct/direct.proto

/*
Package direct is a generated protocol buffer package.

It is generated from these files:
	direct/direct.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package direct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Direct service

type DirectService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type directService struct {
	c    client.Client
	name string
}

func NewDirectService(name string, c client.Client) DirectService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "direct"
	}
	return &directService{
		c:    c,
		name: name,
	}
}

func (c *directService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "Direct.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Direct service

type DirectHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterDirectHandler(s server.Server, hdlr DirectHandler, opts ...server.HandlerOption) error {
	type direct interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type Direct struct {
		direct
	}
	h := &directHandler{hdlr}
	return s.Handle(s.NewHandler(&Direct{h}, opts...))
}

type directHandler struct {
	DirectHandler
}

func (h *directHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.DirectHandler.Hello(ctx, in, out)
}
